### PR TITLE
Remove uuid dependency from setup files

### PR DESCRIPTION
**Pull request by doronbehar**
Follow up to e58b05a47a10791394195b950330709c865e39aa.

### CODE REVIEW

**Comment by doronbehar** [comment]
Build fails with `uuid` installed and without it.

**Comment by doronbehar** [comment]
BTW python has it's builtin `uuid` module which might be useful:

https://docs.python.org/3/library/uuid.html

**Comment by bleykauf** [comment]
Indeed, uuid does not seem to be used anywhere. 

> BTW python has it's builtin `uuid` module which might be useful:
> 
> https://docs.python.org/3/library/uuid.html

The file that is referenced in the `setup.py` should be exactly this library or am I missing something?

**Comment by bleykauf** [comment]
Now also fixed in #277

**Comment by doronbehar** [comment]
> The file that is referenced in the `setup.py` should be exactly this library or am I missing something?

You don't need to specify in `setup.py` dependencies from the standard library, you just import them.

**Comment by bleykauf** [comment]
Closed via #277.

**Pull request closed without merging**
